apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devops

# ~1 is how JSON Pointer escapes /, so the annotation key iam.gke.io/gcp-service-account must be written as iam.gke.io~1gcp-service-account
patches:
  - target:
      kind: Application
      name: argocd-resources
    path: application-patch.yaml
  - target:
      kind: Application
      name: external-secrets
    patch: |
      - op: replace
        path: /spec/project
        value: devops
      - op: replace
        path: /spec/destination/server
        value: https://35.212.195.32
      - op: replace
        path: /spec/source/helm/valuesObject/serviceAccount/annotations/iam.gke.io~1gcp-service-account
        value: "devops@wormhole-proj-id.iam.gserviceaccount.com"
  - target:
      kind: Application
      name: external-secrets-resources
    path: application-patch.yaml
  - target: # configured workload identity for domain name's project and its service account
      kind: Application
      name: cert-manager
    patch: |
      - op: replace
        path: /spec/project
        value: devops
      - op: replace
        path: /spec/destination/server
        value: https://35.212.195.32
      - op: replace
        path: /spec/source/helm/valuesObject/serviceAccount/annotations/iam.gke.io~1gcp-service-account
        value: "devops@wormhole-proj-prd-id.iam.gserviceaccount.com"
  - target:
      kind: Application
      name: cert-manager-resources
    path: application-patch.yaml
  - target:
      kind: Application
      name: opensearch-operator
    patch: |
      - op: replace
        path: /spec/source/helm/valuesObject/manager/dnsBase
        value: wormhole
      - op: replace
        path: /spec/project
        value: devops
      - op: replace
        path: /spec/destination/server
        value: https://35.212.195.32
  - target:
      kind: Application
      name: external-dns-public
    patch: |
      - op: replace
        path: /spec/project
        value: devops
      - op: replace
        path: /spec/destination/server
        value: https://35.212.195.32
      - op: replace
        path: /spec/destination/namespace
        value: external-dns-public
      - op: replace
        path: /spec/source/helm/valuesObject/serviceAccount/annotations/iam.gke.io~1gcp-service-account
        value: "devops@wormhole-proj-prd-id.iam.gserviceaccount.com"
      - op: add
        path: /spec/source/helm/valuesObject/domainFilters/0
        value: "kquiet.org"
      - op: add
        path: /spec/source/helm/valuesObject/extraArgs/0
        value: "--google-project=wormhole-proj-prd-id"
      - op: add
        path: /spec/source/helm/valuesObject/extraArgs/1
        value: "--google-zone-visibility=public"
  - target:
      kind: Application
      name: external-dns-private
    patch: |
      - op: replace
        path: /spec/project
        value: devops
      - op: replace
        path: /spec/destination/server
        value: https://35.212.195.32
      - op: replace
        path: /spec/destination/namespace
        value: external-dns-private
      - op: replace
        path: /spec/source/helm/valuesObject/serviceAccount/annotations/iam.gke.io~1gcp-service-account
        value: "devops@wormhole-proj-id.iam.gserviceaccount.com"
      - op: add
        path: /spec/source/helm/valuesObject/domainFilters/0
        value: "wormhole"
      - op: add
        path: /spec/source/helm/valuesObject/extraArgs/0
        value: "--google-project=wormhole-proj-id"
      - op: add
        path: /spec/source/helm/valuesObject/extraArgs/1
        value: "--google-zone-visibility=private"
  - target:
      kind: Application
      name: opentelemetry-operator
    patch: |
      - op: replace
        path: /spec/project
        value: devops
      - op: replace
        path: /spec/destination/server
        value: https://35.212.195.32
      - op: replace
        path: /spec/source/helm/valuesObject/manager/collectorImage/repository
        value: asia-east1-docker.pkg.dev/wormhole-proj-id/virtual/otelcol-google
      - op: replace
        path: /spec/source/helm/valuesObject/manager/collectorImage/tag
        value: 0.128.0
      - op: replace
        path: /spec/source/helm/valuesObject/manager/autoInstrumentationImage/python/repository
        value: asia-east1-docker.pkg.dev/wormhole-proj-id/virtual/otel-operator-autoinstrumentation-python
      - op: replace
        path: /spec/source/helm/valuesObject/manager/autoInstrumentationImage/python/tag
        value: 0.54b1
  - target:
      kind: Application
      name: opentelemetry-resources
    path: application-patch.yaml
  - target:
      kind: Application
      name: k8s-cluster-resources
    path: application-patch.yaml