apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-upload
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwx-retain
  volumeMode: Filesystem
  volumeName: need-to-override
