---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-database-credentials
spec:
  secretStoreRef:
    name: gcp-wormhole-dev
    kind: ClusterSecretStore
  refreshInterval: "168h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: need-to-override
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: need-to-override
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-opensearch-credentials
spec:
  secretStoreRef:
    name: gcp-wormhole-dev
    kind: ClusterSecretStore
  refreshInterval: "168h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: wormhole
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: need-to-override
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None