---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-node-transport
spec:
  commonName: opensearch-node-transport
  secretName: opensearch-node-transport
  duration: 17520h # 730 days
  renewBefore: 2160h # 90 days
  privateKey:
    algorithm: RSA
    encoding: PKCS8 # required by OpenSearch Security, it can't handle PKCS1 (which is the default of cert-manager
    rotationPolicy: Always
    size: 4096
  usages:
  - server auth
  - client auth
  issuerRef:
    name: wormhole-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-node-http
spec:
  commonName: opensearch-node-http
  secretName: opensearch-node-http
  dnsNames:
  - opensearch-cluster
  duration: 17520h # 730 days
  renewBefore: 2160h # 90 days
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 4096
  usages:
  - digital signature
  - key encipherment
  issuerRef:
    name: wormhole-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-cert
spec:
  commonName: opensearch-admin
  secretName: opensearch-admin-cert
  duration: 17520h # 730 days
  renewBefore: 2160h # 90 days
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 4096
  usages:
  - server auth
  - client auth
  issuerRef:
    name: wormhole-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-admin-credentials
spec:
  secretStoreRef:
    name: gcp-wormhole-dev
    kind: ClusterSecretStore
  refreshInterval: "168h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: admin
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: need-to-override
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-securityconfig
spec:
  secretStoreRef:
    name: gcp-wormhole-dev
    kind: ClusterSecretStore
  refreshInterval: "168h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        action_groups.yml: |-
          _meta:
            type: "actiongroups"
            config_version: 2
        allowlist.yml: |-
          _meta:
            type: "allowlist"
            config_version: 2
          config:
            enabled: false
        internal_users.yml: |-
          _meta:
            type: "internalusers"
            config_version: 2
          admin:
            hash: "{{ .opensearchAdminPwdHash }}"
            reserved: true
            backend_roles:
            - "admin"
            description: "admin user"
        nodes_dn.yml: |-
          _meta:
            type: "nodesdn"
            config_version: 2
        whitelist.yml: |-
          _meta:
            type: "whitelist"
            config_version: 2
          config:
            enabled: false
        tenants.yml: |-
          _meta:
            type: "tenants"
            config_version: 2
        roles_mapping.yml: |-
          _meta:
            type: "rolesmapping"
            config_version: 2
          all_access:
            reserved: false
            backend_roles:
            - "admin"
            description: "Maps admin to all_access"
          own_index:
            reserved: false
            users:
            - "*"
            description: "Allow full access to an index named like the username"
          readall:
            reserved: false
            backend_roles:
            - "readall"
          anonymous_users_role:
            reserved: false
            hidden: false
            backend_roles:
            - "opendistro_security_anonymous_backendrole"
        roles.yml: |-
          _meta:
            type: "roles"
            config_version: 2
          anonymous_users_role:
            reserved: false
            hidden: false
            cluster_permissions:
            - "cluster:monitor/health"
        config.yml: |-
          _meta:
            type: "config"
            config_version: "2"
          config:
            dynamic:
              http:
                anonymous_auth_enabled: true
              authc:
                basic_internal_auth_domain:
                  http_enabled: true
                  transport_enabled: true
                  order: "4"
                  http_authenticator:
                    type: basic
                    challenge: true
                  authentication_backend:
                    type: intern
  data:
  - secretKey: opensearchAdminPwdHash
    remoteRef:
      key: need-to-override