apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llm-azure-openai
spec:
  secretStoreRef:
    name: gcp-wormhole-dev
    kind: ClusterSecretStore
  refreshInterval: "168h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        AZURE_OPENAI_API_KEY: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: need-to-override
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None