apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 30
        type: Percent
        value: 25
      stabilizationWindowSeconds: 0
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 2
      - periodSeconds: 15
        type: Percent
        value: 50
      selectPolicy: Max
      stabilizationWindowSeconds: 0