apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gateway_route_policy.yaml

namespace: wormhole-dev

patches:
  - target:
      kind: ExternalSecret
      name: llm-azure-openai
    patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: dev-azure-openai-api-key
  - target:
      kind: Deployment
      name: llm
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: asia-east1-docker.pkg.dev/wormhole-proj-id/virtual/wormhole-llm:0.1.0
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 1
  - target:
      kind: Service
      name: llm
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 1
  - target:
      kind: Gateway
      name: llm
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 2
      - op: add
        path: /spec/listeners/0/hostname
        value: llm.dev.wormhole
  - target:
      kind: HTTPRoute
      name: llm
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 2
  - target:
      kind: HealthCheckPolicy
      name: llm
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 2
  - target:
      kind: GCPBackendPolicy
      name: llm
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 2
      - op: add
        path: /spec/default/securityPolicy
        value: wormhole-backend-asia-east1-internal
  - target:
      kind: HorizontalPodAutoscaler
      name: llm
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: 3
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 4
      - op: add
        path: /spec/metrics/1
        value:
          type: Object
          object:
            describedObject:
              kind: Service
              name: llm
            metric:
              name: "autoscaling.googleapis.com|gclb-capacity-fullness"
            target:
              averageValue: 70
              type: AverageValue
