apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
spec:
  project: need-to-override
  source:
    repoURL: need-to-override
    path: apps/devops/external-secrets-resources/overlays/dev
    targetRevision: HEAD
  destination:
    server: need-to-override
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true