apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: need-to-override
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.16.2
    helm:
      valuesObject:
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: need-to-override
        global:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: cloud.google.com/gke-provisioning
                    operator: In
                    values:
                    - spot
                weight: 100
          tolerations:
          - key: cloud.google.com/gke-spot
            operator: Equal
            value: "true"
            effect: NoSchedule
  destination:
    server: need-to-override
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
