apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-resources
spec:
  project: need-to-override
  source:
    repoURL: need-to-override
    path: apps/devops/cert-manager-resources/overlays/dev
    targetRevision: HEAD
  destination:
    server: need-to-override
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      name: wormhole-root-ca-tls
      jsonPointers:
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/data/1/remoteRef/conversionStrategy
        - /spec/data/1/remoteRef/decodingStrategy
        - /spec/data/1/remoteRef/metadataPolicy
