apiVersion: v1
kind: PersistentVolume
metadata:
  name: wormhole-dev-backend-upload
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: filestore.csi.storage.gke.io
    volumeAttributes:
      ip: 192.168.186.218
      volume: vol1
      protocol: NFS_V3
    volumeHandle: modeInstance/asia-east1-c/pvc-d5be9b8f-fbdd-4876-bfaf-3ad13ca8daa4/vol1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwx-retain
  volumeMode: Filesystem