apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: devops

patches:
  - target:
      kind: StorageClass
      name: premium-rwx-retain
    path: storage-class-network-patch.yaml
  - target:
      kind: StorageClass
      name: standard-rwx-retain
    path: storage-class-network-patch.yaml
  - target:
      kind: StorageClass
      name: enterprise-rwx-retain
    path: storage-class-network-patch.yaml
  - target:
      kind: StorageClass
      name: enterprise-multishare-rwx-retain
    path: storage-class-network-patch.yaml
  - target:
      kind: StorageClass
      name: zonal-rwx-retain
    path: storage-class-network-patch.yaml