apiVersion: v1
kind: Service
metadata:
  name: opensearch-tcp
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    opster.io/opensearch-cluster: opensearch-cluster
