apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-opensearch-cluster-resources.yaml
  - app-ocr.yaml
  - app-preprocessing.yaml
  - app-frontend.yaml
  - app-embedding.yaml
  - app-llm.yaml
  - app-reranker.yaml
  - app-backend.yaml
